config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  root 'homes#top'
  get 'mypage', to: 'homes#mypage'
  get 'search', to: 'searches#search'
  resources :books
  get 'booksearch', to: 'books#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  
  def new
     @book = Book.new
     
    if params[:keyword].present?
      require 'net/http'
      url = 'https://www.googleapis.com/books/v1/volumes?q='
      request = url + params[:keyword]
      enc_str = URI.encode(request)
      uri = URI.parse(enc_str)
      json = Net::HTTP.get(uri)
      @bookjson = JSON.parse(json)

      count = 5
      @books = Array.new(count).map{Array.new(4)}
      count.times do |x|
        @books[x][0] = @bookjson.dig("items", x, "volumeInfo", "title")
        @books[x][1] = @bookjson.dig("items", x, "volumeInfo", "imageLinks", "thumbnail")
        @books[x][2] = @bookjson.dig("items", x, "volumeInfo", "authors")
        @books[x][2] = @books[x][2].join(',') if @books[x][2] #複数著者をカンマで区切る
        @books[x][3] = @bookjson.dig("items", x, "volumeInfo", "industryIdentifiers", 0, "identifier")
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
     @book = Book.new

    if params[:keyword].present?
      require 'net/http'
      url = 'https://www.googleapis.com/books/v1/volumes?q='
      request = url + params[:keyword]
      enc_str = URI.encode(request)
      uri = URI.parse(enc_str)
      json = Net::HTTP.get(uri)
      @bookjson = JSON.parse(json)

      count = 5
      @books = Array.new(count).map{Array.new(4)}
      count.times do |x|
        @books[x][0] = @bookjson.dig("items", x, "volumeInfo", "title")
        @books[x][1] = @bookjson.dig("items", x, "volumeInfo", "imageLinks", "thumbnail")
        @books[x][2] = @bookjson.dig("items", x, "volumeInfo", "authors")
        @books[x][2] = @books[x][2].join(',') if @books[x][2] #複数著者をカンマで区切る
        @books[x][3] = @bookjson.dig("items", x, "volumeInfo", "industryIdentifiers", 0, "identifier")
      end
    end

    @title = params[:title] if params[:title].present?
    @code = params[:code] if params[:code].present?
    @author = params[:author] if params[:author].present?
    @image = params[:image] if params[:image].present?

  end

  def create
    @book = Book.new(book_params)
    binding.pry
    @book.save
    redirect_to book_path(@book.id)
  end

  def show
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :code, :author, :image)
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/new.html.erb
<h1>書籍の新規登録</h1>
<%= form_tag('/booksearch', method: :get) do %>
    <div class="input-group">
        <%= search_field_tag "keyword", params[:keyword], class:"form-controll", placeholder:"キーワード検索" %>
        <span class="input-group-btn">
            <%= submit_tag "検索", class:"btn btn-primary" %>
        </span>
    </div>
<% end %>
<h2>検索結果</h2>
<% if @books.present? %>
    <% @books.each do |book| %>
        <image src="<%= book[1] %>" width="40" vspace="2">
        <%= link_to book[0], controller: "books", action: "new", title: book[0], code: book[3], author: book[2], image: book[1] %> |
        <%= book[2] %> |
        <%= book[3] %> <br>
    <% end %>
<% end %>

<%= form_with scope: :book, url: books_path, local: true do |form| %>
    <%#= render 'shared/error_messages' %>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-controll', value: "#{@title}" %>

    <%= form.label :author %>
    <%= form.text_field :author, class: "form-controll", value: "#{@author}" %>

    <%= form.hidden_field :image, class: "form-controll", value: "#{@image}" %>

    <%= form.submit "Save Book", class: "btn btn-primary" %>

<% end %>

app/views/books/show.html.erb
<%= @book.image %>
<%= @book.title %>
<%= @book.author %>